language: node_js
node_js:
  - "10.15.3"

services:
  - docker

sudo: required

before_install:
  - docker build -t jerrylerman/feedback_test -f ./client/Dockerfile.dev ./client

# This is the main script running section. These all must pass (status code 0)
script:
  - docker run -e CI=true jerrylerman/feedback-test npm test -- --watchAll=false

after_success:
  - docker build -t jerrylerman/feedback-nginx ./nginx
  - docker build -t jerrylerman/feedback-express ./express
  # Log in to the docker CLI. Encrypt user credentials at TravisCI
  # Go to the section on multi-docker and go into settings
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take images and push them to docker hub
  - docker push jerrylerman/feedback-nginx
  - docker push jerrylerman/feedback-express

# deploy:
#   provider: elasticbeanstalk
#   region: us-east-1
#   app: multi-docker
#   env: MultiDocker-env
#   bucket_name: elasticbeanstalk-us-east-1-375077564851
#   bucket_path: docker-multi
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key:
#     secure: $AWS_SECRET_KEY
